### ISSUE TITLE
[To-do List]

### ISSUE THREAD

**Issue by Rookie0031** [Rookie0031/Restaurant-in-Pohang#7]
## 기능 개선
- [x] URL 이미지 업데이트 속도 저하 문제 개선하기

## 버전 업데이트 사항

- [x] 로고 교체
- [ ] 아쉽게도 원하는 맛집이 없어요... UI 업데이트
- [ ] 음식 클릭시, 세부 사항 뷰 UI 업데이트

## 포트폴리오 업데이트 사항

- [x] 데이터 플로우 정리(Visualization)
- [ ] 노션 DB 데이터 관리 이유 정리 (음식점 업데이트 및 추후 카테고리 추가시 용이)
- [ ] 즐겨 찾기 데이터 저장 이유 정리 (UserDefault, CoreData 등)
