### ISSUE TITLE
프로젝트 관리 To-do List 

### ISSUE THREAD

**Issue by Rookie0031** [Rookie0031/Restaurant-in-Pohang#8]
### ReadMe 설명 개선
- [x] !!! 왜 UI 작업에 SwiftUI를 사용하게 되었는가? UIkit과 비교해서 어떤 메리트가 있어서 이를 쓰기로 판단했는가?  적어주기
- [ ] !!! NukeUI에 대한 링크를 넣고 SwiftUI의 어떤 부분때문에 이를 사용하게 되었는지 자세하게 기술하기
- [ ] !!! async await 말고 다른 선택지가 있는데 왜 이것을 써야했는지 설명하기
- [ ] !!! FileManager가 어떤 것인지 설명 적어주기 (영구 저장이라는 키워드 다른말로 바꾸기, 맥락상 케싱을 위해 썼다고는 등 )
- [ ] !! 데이터를 왜 제이슨 구조로 저장하는지 설명적어주기
- [ ] !!! 왜 MVVM 구조를 채택하게 되었는지 다른 구조랑 비교해서 설명하기
- [ ] !! 데이터 플로우 차트 수정하기 (FileManager에 저장되는 것과 NotionDB는 결국 같은 데이터라는 것을 보여줘야함)
- [ ] ! Design Skill에 HIG Component를 잘 적어주기 (원론적인 디자인 이야기는 지양)

### Code 개선
- [ ] !!! ViewModel은 하나의 뷰에 대한 책임을 가진다. 따라서 각 뷰별 ViewModel을 가지는 구조로 바꿔야함
- [ ] ! 반복적인 구조의 코드를 최대한 없애보자 
- [ ] !! server에서 데이터를 가져오는 것과 local에서 가져오는 함수는 따로 관리되어야 한다. 

### 느낀점 작성
- [ ] !!! 지저분한 코드를 받고 이를 개선하면서 했던 삽질과 배운점들을 리스트업하기
- [ ] !!! 한계점 적기, 시간이 없어서 프로젝트를 종료하지만 나중에 이런 부분들은 반영해서 코드를 짜야겠다 하는 부분 등을 발견해서 적기

## Tips
- 자신의 코드에도 리뷰를 한다고 생각하자
- 혼자 작업하더라도 PR을 작성하는 연습을 하자 
- PR에는 스크린샷보다는 코드 부분을 링크로 걸자 (보는 사람이 클릭해서 페이지 열어보고 바로 어떤 부분인지 찾을 수 있게!)
